name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21' 

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload to cPanel
      uses: SamKirkland/ftp-deploy-action@4.0.0
      with:
        server: ${{ secrets.CPANEL_SERVER }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        local-dir: ./dist  # Sesuaikan dengan lokasi build Anda
        remote-dir: /path/to/remote/directory  # Sesuaikan dengan path di cPanel
