name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai jika berbeda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up FTP Deployment
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        remote-dir: /public_html/ # Ganti dengan path ke direktori di cPanel Anda
        clean: true  # Hapus file di server yang tidak ada di lokal
